// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfvqvtgtfaezicrirylc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmdnF2dGd0ZmFlemljcmlyeWxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMjQyNzEsImV4cCI6MjA1NzkwMDI3MX0.BAcGTrVXMUmykx9JRzUuJOrOvqZ13iEvRowSwfk69eI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);